### ISSUE TITLE
Wave statistics

### ISSUE THREAD

**Issue by mrocha94** [uspgamedev/JellyArena#22]
Defines which we want to gather:
- [x] Damage to player
- [x] Player mobility
- [x] Wave time

We can get information for traps too

**Comment by fbrigalante** [comment]
I think all of these statistics must be normalized based on how many of each action was present on a specific wave.

For example: Consider a wave with 10 melee attackers and 1 ranged attacker. It's very likely that the melee attackers will deal more damage, but it doesn't mean that the melee attackers are more efficient.

**Comment by mrocha94** [comment]
Closed #48
